<a href="https://colab.research.google.com/github/mha142/my_pytorch_tutorials/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
print(tensor_A)
print(tensor_A.shape)

tensor([[0.2219, 0.8038, 0.8611, 0.3858, 0.2921, 0.2423, 0.8139],
        [0.3727, 0.5821, 0.4247, 0.2394, 0.3396, 0.1246, 0.6092],
        [0.7787, 0.5590, 0.1875, 0.7786, 0.4040, 0.0194, 0.9671],
        [0.9815, 0.0483, 0.0211, 0.5819, 0.7671, 0.7058, 0.8687],
        [0.8657, 0.9125, 0.3487, 0.2179, 0.7088, 0.0961, 0.4237],
        [0.4996, 0.3551, 0.3422, 0.8731, 0.0693, 0.2818, 0.9704],
        [0.3491, 0.0732, 0.0821, 0.3542, 0.3770, 0.0655, 0.3381]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor_B = torch.rand(1, 7)
# Perform matrix multiplication
tensor_C = torch.matmul(tensor_B, tensor_A)
print(tensor_C)
print(tensor_C.shape)

tensor([[1.8183, 1.8627, 1.3450, 1.8873, 1.1705, 0.5991, 2.7434]])
torch.Size([1, 7])


In [8]:
tensor_D = torch.matmul(tensor_A, tensor_B.T)
print(tensor_D)
print(tensor_D.shape)

tensor([[1.9196],
        [1.3455],
        [1.4919],
        [1.5874],
        [1.8503],
        [1.4220],
        [0.5953]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_E = torch.rand(3, 3)
tensor_F = torch.rand(3, 2)

# Matrix multiply tensors
tensor_G = torch.matmul(tensor_E, tensor_F)
print(tensor_G)
print(tensor_G.shape)


# Matrix multiply tensors


tensor([[0.6373, 0.2163],
        [0.3141, 0.2393],
        [0.7469, 0.3249]])
torch.Size([3, 2])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
if torch.cuda.is_available():
  torch.manual_seed(1234)
  print("GPU is available")
else:
  print("GPU is not available")

GPU is available



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_H = torch.rand(2, 3).to(device)
tensor_I = torch.rand(2, 3).to(device)
print(tensor_H)
print(tensor_I)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_H, tensor_I.T)
print(result)
print(result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print(torch.max(result))

# Find min
print(torch.min(result))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
