<a href="https://colab.research.google.com/github/mha142/my_pytorch_tutorials/blob/main/pytorch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7]) # no of dimensions = number of square bracketes [] = 1D
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
t = torch.tensor([[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]])

t.shape

torch.Size([3, 3])

In [19]:
t = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
t.shape

torch.Size([1, 3, 3])

In [21]:
t = torch.tensor([[[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]]])
t.shape


torch.Size([1, 1, 3, 3])

### Random Tensors
## Random Tensors

start with random numbers > look @ data > update random numbers > look @ data > update random numbers

In [ ]:
#create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8233, 0.8825, 0.2674, 0.1509],
        [0.1895, 0.2047, 0.1503, 0.6033],
        [0.9993, 0.9500, 0.1042, 0.3924]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(size=(3, 3))

tensor([[0.1781, 0.3108, 0.0158],
        [0.4210, 0.8553, 0.3401],
        [0.8640, 0.5605, 0.3363]])

In [ ]:
torch.rand(3,3)

tensor([[0.6269, 0.3764, 0.4280],
        [0.6923, 0.1718, 0.4631],
        [0.1129, 0.4705, 0.9963]])

###zeros and ones


In [ ]:
##zeros and ones
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype #default data type

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

###create a range of tensors and tensors-like

In [ ]:
torch.arange(0, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__


'2.5.1+cu121'

In [ ]:
one_to_ten = torch.arange(start=0, end=20, step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten) # we get zeros in the same shape as one_to_ten
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, #torch.float16  #what datatype is the tensor (e.g. float32 or float16)
                               device= None, #cpu #cuda #what device is your tensor on
                               requires_grad= False #whether or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
#change tensor data type from 32 to 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)#dtype=torch.int64 #dtype=torch.long
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor
  
  1. Tensors not right datatype - to do get datatype from a tensor, can use tensopr.dtype
  2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
  3. Tensors not on the right device - to get device from a tensor, can use tensor.device
  

In [ ]:
#create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7277, 0.8480, 0.5590, 0.3003],
        [0.9431, 0.7678, 0.5508, 0.1251],
        [0.0599, 0.1013, 0.0307, 0.4791]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7277, 0.8480, 0.5590, 0.3003],
        [0.9431, 0.7678, 0.5508, 0.1251],
        [0.0599, 0.1013, 0.0307, 0.4791]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
#manipulating tensors (tesnor opertions)

Tensor Operations include:
Addition
Subtraction
Multiplication(element-wise)
Division
Matrix multiplication

In [ ]:
#create a tensor to add 10 ot it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10
#IF YOU assign tensor = tensor * 10
#then the next cell that include print of tensor will produce 10, 20, 30 instead of 1, 2, 3

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
two main ways of performing multiplication in neural network and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)


source: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Rules to satisfy matrix multiplication:
1. the **inner dimensions** must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work >> output shape is (2, 2)

(3, 2) @ (2, 3) will work >> output shape is (3, 3)

2. the resulting shape has the shape of the outer dimensions

Try: http://matrixmultiplication.xyz/



In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#element wise multiplication
tensor


tensor([1, 2, 3])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.23 ms, sys: 0 ns, total: 4.23 ms
Wall time: 4.46 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.3 ms, sys: 0 ns, total: 1.3 ms
Wall time: 1.21 ms


tensor(14)

#One of the most common errors in deep learning: shape errors


In [ ]:
#shapes for mtrix multiplication
tensor_A = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

###to fix the tensor shape issuees: manipulate the tensor shape
- transpose the shape of one of the tensors (switch the dimensions of a given tensor)
- reshape the tensor

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torchmat = torch.matmul(tensor_A, tensor_B.T)
torchmat

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torchmat.shape

torch.Size([3, 3])

#Tensor aggregation: find mean, max, mean, sum, ..etc.

In [ ]:
#create a tensor
x = torch.arange(1 , 100, 10)
x, x.dtype


(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

#finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin()
#the result is the index of the minimum value

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all '1' dimensions from a tensor
* unsqueeze - add a '1' dimension to a target tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [2]:
import torch
x = torch.arange(1., 10.)#9 elements
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [4]:
#add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [5]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [6]:
x_reshaped = x.reshape(2, 9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [7]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [8]:
#change the view
x = torch.arange(1., 11.) #10 elements
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [9]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [12]:
x = torch.arange(1., 10.)#9 elements
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [25]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [26]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [27]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [41]:
x, x.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [32]:
y = torch.squeeze(x)
y

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
#previous cell output is the same as the output of this cell
y = torch.squeeze(x, 0)
y

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
y = torch.squeeze(x_reshaped, 0)
y, y.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
y = torch.squeeze(x_reshaped, 1)
y, y.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
#torch.squeeze()- removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [52]:
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
x_reshaped.squeeze().shape

torch.Size([9])

In [56]:
# torch unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor squeezed: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor unsqueezed: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
#

Previous tensor squeezed: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor unsqueezed: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [62]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [66]:
# torch.permute - rearranges the dimensions of a target tnesor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # h, w, color channels

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #color channels, h, w


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
