<a href="https://colab.research.google.com/github/mha142/my_pytorch_tutorials/blob/main/pytorch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [6]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [10]:
#vector
vector = torch.tensor([7, 7]) # no of dimensions = number of square bracketes [] = 1D
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [20]:
vector.shape

torch.Size([2])

In [14]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [22]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
## Random Tensors

start with random numbers > look @ data > update random numbers > look @ data > update random numbers

In [4]:
#create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8233, 0.8825, 0.2674, 0.1509],
        [0.1895, 0.2047, 0.1503, 0.6033],
        [0.9993, 0.9500, 0.1042, 0.3924]])

In [5]:
random_tensor.ndim

2

In [7]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [8]:
torch.rand(size=(3, 3))

tensor([[0.1781, 0.3108, 0.0158],
        [0.4210, 0.8553, 0.3401],
        [0.8640, 0.5605, 0.3363]])

In [9]:
torch.rand(3,3)

tensor([[0.6269, 0.3764, 0.4280],
        [0.6923, 0.1718, 0.4631],
        [0.1129, 0.4705, 0.9963]])

###zeros and ones


In [11]:
##zeros and ones
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
ones.dtype #default data type

torch.float32

In [15]:
random_tensor.dtype

torch.float32

###create a range of tensors and tensors-like

In [21]:
torch.arange(0, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.__version__


'2.5.1+cu121'

In [22]:
one_to_ten = torch.arange(start=0, end=20, step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten) # we get zeros in the same shape as one_to_ten
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, #torch.float16  #what datatype is the tensor (e.g. float32 or float16)
                               device= None, #cpu #cuda #what device is your tensor on
                               requires_grad= False #whether or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [4]:
float_32_tensor.dtype

torch.float32

In [5]:
#change tensor data type from 32 to 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [6]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [7]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)#dtype=torch.int64 #dtype=torch.long
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [8]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor
  
  1. Tensors not right datatype - to do get datatype from a tensor, can use tensopr.dtype
  2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
  3. Tensors not on the right device - to get device from a tensor, can use tensor.device
  

In [10]:
#create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7277, 0.8480, 0.5590, 0.3003],
        [0.9431, 0.7678, 0.5508, 0.1251],
        [0.0599, 0.1013, 0.0307, 0.4791]])

In [15]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7277, 0.8480, 0.5590, 0.3003],
        [0.9431, 0.7678, 0.5508, 0.1251],
        [0.0599, 0.1013, 0.0307, 0.4791]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
#manipulating tensors (tesnor opertions)

Tensor Operations include:
Addition
Subtraction
Multiplication(element-wise)
Division
Matrix multiplication

In [21]:
#create a tensor to add 10 ot it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [22]:
# multiply tensor by 10
tensor * 10
#IF YOU assign tensor = tensor * 10
#then the next cell that include print of tensor will produce 10, 20, 30 instead of 1, 2, 3

tensor([10, 20, 30])

In [23]:
tensor

tensor([1, 2, 3])

In [24]:
tensor - 10

tensor([-9, -8, -7])

In [25]:
#try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [26]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
two main ways of performing multiplication in neural network and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)


source: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Rules to satisfy matrix multiplication:
1. the **inner dimensions** must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work >> output shape is (2, 2)

(3, 2) @ (2, 3) will work >> output shape is (3, 3)

2. the resulting shape has the shape of the outer dimensions

Try: http://matrixmultiplication.xyz/



In [39]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [29]:
#element wise multiplication
tensor


tensor([1, 2, 3])

In [30]:
tensor * tensor

tensor([1, 4, 9])

In [32]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [33]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [38]:
tensor @ tensor

tensor(14)

In [35]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.23 ms, sys: 0 ns, total: 4.23 ms
Wall time: 4.46 ms


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.3 ms, sys: 0 ns, total: 1.3 ms
Wall time: 1.21 ms


tensor(14)